<!DOCTYPE html>

<html>
    <head>
        <title>Listar categorias</title>
        <meta charset="UTF-8">
    </head>
    <body>
        <h1>Categorias</h1>
        
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Categoria</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{idcategoria}}</td>
                    <td>{{categoria}}</td>
                    <td><a href="categoria-cadastrar.php">[Editar]</a></td>
                </tr>
            </tbody>
        </table>
    </body>
</html>
