<!DOCTYPE html>

<html>
    <head>
        <title>Cadastrar categoria</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <h1><?php echo $this->getValor('nome'); ?></h1>
        
        <form action="categoria-cadastrar.php" method="post">
            Categoria:
            <input type="text" name="categoria">
            <br>
            <input type="submit" value="Cadastrar">
        </form>
    </body>
</html>
