<!DOCTYPE html>

<html>
    <head>
        <title>Listar categorias</title>
        <meta charset="UTF-8">
    </head>
    <body>
        <h1>Categorias</h1>
        
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Categoria</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->getValor('categorias') as $cat) {?>
                <tr>
                    <td><?php echo $cat->idcategoria; ?></td>
                    <td><?php echo $cat->categoria; ?></td>
                    <td><a href="categoria-editar.php?idcategoria=<?php echo $cat->idcategoria; ?>">[Editar]</a></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </body>
</html>
