<!DOCTYPE html>

<html>
    <head>
        <title>Cadastrar post</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <h1>Cadastrar post</h1>
        
        <?php
        $erro = $this->getValor('erro');
        if ($erro != '') {
        ?>
        <p>Mensagem de erro: <?php echo $erro; ?></p>
        <?php
        }
        ?>
        
        <form action="post-cadastrar.php" method="post">
            Título:
            <input type="text" name="titulo">
            <br>
            
            Categoria:
            <select name="idcategoria">
                <?php
                $categorias = $this->getValor('categorias');
                
                foreach($categorias as $categoria) {
                ?>
                <option value="<?php echo $categoria->idcategoria; ?>">
                    <?php echo $categoria->categoria; ?></option>
                <?php } ?>
            </select>
            <br>
            
            Texto:
            <textarea name="texto" rows="5"></textarea>
            <br>
            <input type="submit" value="Cadastrar">
        </form>
    </body>
</html>
