<?php
// https://api.github.com/search/users?q=chiqui

header('content-type:application/json; charset=utf-8;');
?>
{
  "total_count": 52,
  "incomplete_results": false,
  "items": [
    {
      "login": "chiquiesteban",
      "id": 2955186,
      "avatar_url": "https://avatars.githubusercontent.com/u/2955186?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquiesteban",
      "html_url": "https://github.com/chiquiesteban",
      "followers_url": "https://api.github.com/users/chiquiesteban/followers",
      "following_url": "https://api.github.com/users/chiquiesteban/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquiesteban/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquiesteban/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquiesteban/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquiesteban/orgs",
      "repos_url": "https://api.github.com/users/chiquiesteban/repos",
      "events_url": "https://api.github.com/users/chiquiesteban/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquiesteban/received_events",
      "type": "User",
      "site_admin": false,
      "score": 46.379845
    },
    {
      "login": "chiquitto",
      "id": 2262702,
      "avatar_url": "https://avatars.githubusercontent.com/u/2262702?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquitto",
      "html_url": "https://github.com/chiquitto",
      "followers_url": "https://api.github.com/users/chiquitto/followers",
      "following_url": "https://api.github.com/users/chiquitto/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquitto/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquitto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquitto/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquitto/orgs",
      "repos_url": "https://api.github.com/users/chiquitto/repos",
      "events_url": "https://api.github.com/users/chiquitto/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquitto/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.631872
    },
    {
      "login": "chiquitinxx",
      "id": 879681,
      "avatar_url": "https://avatars.githubusercontent.com/u/879681?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquitinxx",
      "html_url": "https://github.com/chiquitinxx",
      "followers_url": "https://api.github.com/users/chiquitinxx/followers",
      "following_url": "https://api.github.com/users/chiquitinxx/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquitinxx/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquitinxx/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquitinxx/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquitinxx/orgs",
      "repos_url": "https://api.github.com/users/chiquitinxx/repos",
      "events_url": "https://api.github.com/users/chiquitinxx/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquitinxx/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.631872
    },
    {
      "login": "chiqui",
      "id": 375695,
      "avatar_url": "https://avatars.githubusercontent.com/u/375695?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiqui",
      "html_url": "https://github.com/chiqui",
      "followers_url": "https://api.github.com/users/chiqui/followers",
      "following_url": "https://api.github.com/users/chiqui/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiqui/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiqui/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiqui/subscriptions",
      "organizations_url": "https://api.github.com/users/chiqui/orgs",
      "repos_url": "https://api.github.com/users/chiqui/repos",
      "events_url": "https://api.github.com/users/chiqui/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiqui/received_events",
      "type": "User",
      "site_admin": false,
      "score": 16.564228
    },
    {
      "login": "chiqui3d",
      "id": 2461400,
      "avatar_url": "https://avatars.githubusercontent.com/u/2461400?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiqui3d",
      "html_url": "https://github.com/chiqui3d",
      "followers_url": "https://api.github.com/users/chiqui3d/followers",
      "following_url": "https://api.github.com/users/chiqui3d/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiqui3d/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiqui3d/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiqui3d/subscriptions",
      "organizations_url": "https://api.github.com/users/chiqui3d/orgs",
      "repos_url": "https://api.github.com/users/chiqui3d/repos",
      "events_url": "https://api.github.com/users/chiqui3d/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiqui3d/received_events",
      "type": "User",
      "site_admin": false,
      "score": 14.14492
    },
    {
      "login": "Dyanniza",
      "id": 8669858,
      "avatar_url": "https://avatars.githubusercontent.com/u/8669858?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Dyanniza",
      "html_url": "https://github.com/Dyanniza",
      "followers_url": "https://api.github.com/users/Dyanniza/followers",
      "following_url": "https://api.github.com/users/Dyanniza/following{/other_user}",
      "gists_url": "https://api.github.com/users/Dyanniza/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Dyanniza/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Dyanniza/subscriptions",
      "organizations_url": "https://api.github.com/users/Dyanniza/orgs",
      "repos_url": "https://api.github.com/users/Dyanniza/repos",
      "events_url": "https://api.github.com/users/Dyanniza/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Dyanniza/received_events",
      "type": "User",
      "site_admin": false,
      "score": 10.662574
    },
    {
      "login": "chiquirf",
      "id": 12784106,
      "avatar_url": "https://avatars.githubusercontent.com/u/12784106?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquirf",
      "html_url": "https://github.com/chiquirf",
      "followers_url": "https://api.github.com/users/chiquirf/followers",
      "following_url": "https://api.github.com/users/chiquirf/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquirf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquirf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquirf/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquirf/orgs",
      "repos_url": "https://api.github.com/users/chiquirf/repos",
      "events_url": "https://api.github.com/users/chiquirf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquirf/received_events",
      "type": "User",
      "site_admin": false,
      "score": 8.486952
    },
    {
      "login": "chiquitta",
      "id": 2586794,
      "avatar_url": "https://avatars.githubusercontent.com/u/2586794?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquitta",
      "html_url": "https://github.com/chiquitta",
      "followers_url": "https://api.github.com/users/chiquitta/followers",
      "following_url": "https://api.github.com/users/chiquitta/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquitta/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquitta/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquitta/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquitta/orgs",
      "repos_url": "https://api.github.com/users/chiquitta/repos",
      "events_url": "https://api.github.com/users/chiquitta/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquitta/received_events",
      "type": "User",
      "site_admin": false,
      "score": 7.07246
    },
    {
      "login": "chiquita0001",
      "id": 7631472,
      "avatar_url": "https://avatars.githubusercontent.com/u/7631472?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquita0001",
      "html_url": "https://github.com/chiquita0001",
      "followers_url": "https://api.github.com/users/chiquita0001/followers",
      "following_url": "https://api.github.com/users/chiquita0001/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquita0001/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquita0001/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquita0001/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquita0001/orgs",
      "repos_url": "https://api.github.com/users/chiquita0001/repos",
      "events_url": "https://api.github.com/users/chiquita0001/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquita0001/received_events",
      "type": "User",
      "site_admin": false,
      "score": 7.07246
    },
    {
      "login": "chiqui862",
      "id": 10344408,
      "avatar_url": "https://avatars.githubusercontent.com/u/10344408?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiqui862",
      "html_url": "https://github.com/chiqui862",
      "followers_url": "https://api.github.com/users/chiqui862/followers",
      "following_url": "https://api.github.com/users/chiqui862/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiqui862/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiqui862/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiqui862/subscriptions",
      "organizations_url": "https://api.github.com/users/chiqui862/orgs",
      "repos_url": "https://api.github.com/users/chiqui862/repos",
      "events_url": "https://api.github.com/users/chiqui862/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiqui862/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquinho",
      "id": 10381813,
      "avatar_url": "https://avatars.githubusercontent.com/u/10381813?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquinho",
      "html_url": "https://github.com/chiquinho",
      "followers_url": "https://api.github.com/users/chiquinho/followers",
      "following_url": "https://api.github.com/users/chiquinho/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquinho/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquinho/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquinho/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquinho/orgs",
      "repos_url": "https://api.github.com/users/chiquinho/repos",
      "events_url": "https://api.github.com/users/chiquinho/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquinho/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquiti",
      "id": 10383509,
      "avatar_url": "https://avatars.githubusercontent.com/u/10383509?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquiti",
      "html_url": "https://github.com/chiquiti",
      "followers_url": "https://api.github.com/users/chiquiti/followers",
      "following_url": "https://api.github.com/users/chiquiti/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquiti/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquiti/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquiti/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquiti/orgs",
      "repos_url": "https://api.github.com/users/chiquiti/repos",
      "events_url": "https://api.github.com/users/chiquiti/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquiti/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "Chiquitogamer777OMG",
      "id": 9756382,
      "avatar_url": "https://avatars.githubusercontent.com/u/9756382?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Chiquitogamer777OMG",
      "html_url": "https://github.com/Chiquitogamer777OMG",
      "followers_url": "https://api.github.com/users/Chiquitogamer777OMG/followers",
      "following_url": "https://api.github.com/users/Chiquitogamer777OMG/following{/other_user}",
      "gists_url": "https://api.github.com/users/Chiquitogamer777OMG/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Chiquitogamer777OMG/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Chiquitogamer777OMG/subscriptions",
      "organizations_url": "https://api.github.com/users/Chiquitogamer777OMG/orgs",
      "repos_url": "https://api.github.com/users/Chiquitogamer777OMG/repos",
      "events_url": "https://api.github.com/users/Chiquitogamer777OMG/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Chiquitogamer777OMG/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquini",
      "id": 10437353,
      "avatar_url": "https://avatars.githubusercontent.com/u/10437353?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquini",
      "html_url": "https://github.com/chiquini",
      "followers_url": "https://api.github.com/users/chiquini/followers",
      "following_url": "https://api.github.com/users/chiquini/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquini/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquini/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquini/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquini/orgs",
      "repos_url": "https://api.github.com/users/chiquini/repos",
      "events_url": "https://api.github.com/users/chiquini/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquini/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquitajones",
      "id": 10180973,
      "avatar_url": "https://avatars.githubusercontent.com/u/10180973?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquitajones",
      "html_url": "https://github.com/chiquitajones",
      "followers_url": "https://api.github.com/users/chiquitajones/followers",
      "following_url": "https://api.github.com/users/chiquitajones/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquitajones/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquitajones/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquitajones/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquitajones/orgs",
      "repos_url": "https://api.github.com/users/chiquitajones/repos",
      "events_url": "https://api.github.com/users/chiquitajones/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquitajones/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "Chiqui97",
      "id": 1278096,
      "avatar_url": "https://avatars.githubusercontent.com/u/1278096?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Chiqui97",
      "html_url": "https://github.com/Chiqui97",
      "followers_url": "https://api.github.com/users/Chiqui97/followers",
      "following_url": "https://api.github.com/users/Chiqui97/following{/other_user}",
      "gists_url": "https://api.github.com/users/Chiqui97/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Chiqui97/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Chiqui97/subscriptions",
      "organizations_url": "https://api.github.com/users/Chiqui97/orgs",
      "repos_url": "https://api.github.com/users/Chiqui97/repos",
      "events_url": "https://api.github.com/users/Chiqui97/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Chiqui97/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquis",
      "id": 1342243,
      "avatar_url": "https://avatars.githubusercontent.com/u/1342243?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquis",
      "html_url": "https://github.com/chiquis",
      "followers_url": "https://api.github.com/users/chiquis/followers",
      "following_url": "https://api.github.com/users/chiquis/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquis/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquis/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquis/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquis/orgs",
      "repos_url": "https://api.github.com/users/chiquis/repos",
      "events_url": "https://api.github.com/users/chiquis/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquis/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquitin",
      "id": 4073041,
      "avatar_url": "https://avatars.githubusercontent.com/u/4073041?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquitin",
      "html_url": "https://github.com/chiquitin",
      "followers_url": "https://api.github.com/users/chiquitin/followers",
      "following_url": "https://api.github.com/users/chiquitin/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquitin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquitin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquitin/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquitin/orgs",
      "repos_url": "https://api.github.com/users/chiquitin/repos",
      "events_url": "https://api.github.com/users/chiquitin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquitin/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquin",
      "id": 4401643,
      "avatar_url": "https://avatars.githubusercontent.com/u/4401643?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquin",
      "html_url": "https://github.com/chiquin",
      "followers_url": "https://api.github.com/users/chiquin/followers",
      "following_url": "https://api.github.com/users/chiquin/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquin/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquin/orgs",
      "repos_url": "https://api.github.com/users/chiquin/repos",
      "events_url": "https://api.github.com/users/chiquin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquin/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquiabilla",
      "id": 7274453,
      "avatar_url": "https://avatars.githubusercontent.com/u/7274453?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquiabilla",
      "html_url": "https://github.com/chiquiabilla",
      "followers_url": "https://api.github.com/users/chiquiabilla/followers",
      "following_url": "https://api.github.com/users/chiquiabilla/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquiabilla/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquiabilla/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquiabilla/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquiabilla/orgs",
      "repos_url": "https://api.github.com/users/chiquiabilla/repos",
      "events_url": "https://api.github.com/users/chiquiabilla/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquiabilla/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquicom1",
      "id": 6168035,
      "avatar_url": "https://avatars.githubusercontent.com/u/6168035?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquicom1",
      "html_url": "https://github.com/chiquicom1",
      "followers_url": "https://api.github.com/users/chiquicom1/followers",
      "following_url": "https://api.github.com/users/chiquicom1/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquicom1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquicom1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquicom1/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquicom1/orgs",
      "repos_url": "https://api.github.com/users/chiquicom1/repos",
      "events_url": "https://api.github.com/users/chiquicom1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquicom1/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiqui587",
      "id": 6360846,
      "avatar_url": "https://avatars.githubusercontent.com/u/6360846?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiqui587",
      "html_url": "https://github.com/chiqui587",
      "followers_url": "https://api.github.com/users/chiqui587/followers",
      "following_url": "https://api.github.com/users/chiqui587/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiqui587/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiqui587/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiqui587/subscriptions",
      "organizations_url": "https://api.github.com/users/chiqui587/orgs",
      "repos_url": "https://api.github.com/users/chiqui587/repos",
      "events_url": "https://api.github.com/users/chiqui587/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiqui587/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquita0002",
      "id": 7866557,
      "avatar_url": "https://avatars.githubusercontent.com/u/7866557?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquita0002",
      "html_url": "https://github.com/chiquita0002",
      "followers_url": "https://api.github.com/users/chiquita0002/followers",
      "following_url": "https://api.github.com/users/chiquita0002/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquita0002/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquita0002/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquita0002/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquita0002/orgs",
      "repos_url": "https://api.github.com/users/chiquita0002/repos",
      "events_url": "https://api.github.com/users/chiquita0002/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquita0002/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquisegovia",
      "id": 7725467,
      "avatar_url": "https://avatars.githubusercontent.com/u/7725467?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquisegovia",
      "html_url": "https://github.com/chiquisegovia",
      "followers_url": "https://api.github.com/users/chiquisegovia/followers",
      "following_url": "https://api.github.com/users/chiquisegovia/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquisegovia/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquisegovia/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquisegovia/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquisegovia/orgs",
      "repos_url": "https://api.github.com/users/chiquisegovia/repos",
      "events_url": "https://api.github.com/users/chiquisegovia/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquisegovia/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "ChiquitaRubia",
      "id": 8093188,
      "avatar_url": "https://avatars.githubusercontent.com/u/8093188?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ChiquitaRubia",
      "html_url": "https://github.com/ChiquitaRubia",
      "followers_url": "https://api.github.com/users/ChiquitaRubia/followers",
      "following_url": "https://api.github.com/users/ChiquitaRubia/following{/other_user}",
      "gists_url": "https://api.github.com/users/ChiquitaRubia/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ChiquitaRubia/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ChiquitaRubia/subscriptions",
      "organizations_url": "https://api.github.com/users/ChiquitaRubia/orgs",
      "repos_url": "https://api.github.com/users/ChiquitaRubia/repos",
      "events_url": "https://api.github.com/users/ChiquitaRubia/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ChiquitaRubia/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "Chiquibul",
      "id": 8193620,
      "avatar_url": "https://avatars.githubusercontent.com/u/8193620?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Chiquibul",
      "html_url": "https://github.com/Chiquibul",
      "followers_url": "https://api.github.com/users/Chiquibul/followers",
      "following_url": "https://api.github.com/users/Chiquibul/following{/other_user}",
      "gists_url": "https://api.github.com/users/Chiquibul/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Chiquibul/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Chiquibul/subscriptions",
      "organizations_url": "https://api.github.com/users/Chiquibul/orgs",
      "repos_url": "https://api.github.com/users/Chiquibul/repos",
      "events_url": "https://api.github.com/users/Chiquibul/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Chiquibul/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquitita",
      "id": 8358276,
      "avatar_url": "https://avatars.githubusercontent.com/u/8358276?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquitita",
      "html_url": "https://github.com/chiquitita",
      "followers_url": "https://api.github.com/users/chiquitita/followers",
      "following_url": "https://api.github.com/users/chiquitita/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquitita/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquitita/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquitita/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquitita/orgs",
      "repos_url": "https://api.github.com/users/chiquitita/repos",
      "events_url": "https://api.github.com/users/chiquitita/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquitita/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquilinda",
      "id": 8472374,
      "avatar_url": "https://avatars.githubusercontent.com/u/8472374?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquilinda",
      "html_url": "https://github.com/chiquilinda",
      "followers_url": "https://api.github.com/users/chiquilinda/followers",
      "following_url": "https://api.github.com/users/chiquilinda/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquilinda/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquilinda/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquilinda/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquilinda/orgs",
      "repos_url": "https://api.github.com/users/chiquilinda/repos",
      "events_url": "https://api.github.com/users/chiquilinda/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquilinda/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "chiquis82",
      "id": 8562390,
      "avatar_url": "https://avatars.githubusercontent.com/u/8562390?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chiquis82",
      "html_url": "https://github.com/chiquis82",
      "followers_url": "https://api.github.com/users/chiquis82/followers",
      "following_url": "https://api.github.com/users/chiquis82/following{/other_user}",
      "gists_url": "https://api.github.com/users/chiquis82/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chiquis82/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chiquis82/subscriptions",
      "organizations_url": "https://api.github.com/users/chiquis82/orgs",
      "repos_url": "https://api.github.com/users/chiquis82/repos",
      "events_url": "https://api.github.com/users/chiquis82/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chiquis82/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    },
    {
      "login": "ChiquitaElena",
      "id": 9000136,
      "avatar_url": "https://avatars.githubusercontent.com/u/9000136?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ChiquitaElena",
      "html_url": "https://github.com/ChiquitaElena",
      "followers_url": "https://api.github.com/users/ChiquitaElena/followers",
      "following_url": "https://api.github.com/users/ChiquitaElena/following{/other_user}",
      "gists_url": "https://api.github.com/users/ChiquitaElena/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ChiquitaElena/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ChiquitaElena/subscriptions",
      "organizations_url": "https://api.github.com/users/ChiquitaElena/orgs",
      "repos_url": "https://api.github.com/users/ChiquitaElena/repos",
      "events_url": "https://api.github.com/users/ChiquitaElena/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ChiquitaElena/received_events",
      "type": "User",
      "site_admin": false,
      "score": 5.657968
    }
  ]
}